### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by dimadk24**

### CODE REVIEW

**Comment by dimadk24** [comment]
Based on https://asperitas.vercel.app/

**Comment by dimadk24** [comment]
I would also propose to change spinners to something more common like https://getbootstrap.com/docs/4.2/components/spinners/

Let me know your thoughts

**Review by IlyaTsupryk — APPROVED** [review]
Agree, let's change spinners in next PRs.
This PR looks good, though I see a warning (validateDOMNesting(...): p cannot appear as a descendant of p.) in console. Would be good to fix in future

**Comment by dimadk24** [comment]
> validateDOMNesting(...): \<p\> cannot appear as a descendant of \<p\>.

Fixed, thank you!

**Comment by IlyaTsupryk** [comment]
Great! Let's merge

**Pull request merged**
