### PR TITLE
Use dedicated ipfs server

### PR DESCRIPTION
**Pull request by IlyaTsupryk**

### CODE REVIEW

**Review by dimadk24 — CHANGES_REQUESTED** [review]
Doesn't work on deployed preview instance. I think we need to update vercel env variables. And doesn't work locally because of lack of env variables. Please share them in the common chat, so all guys can define them in their .env.local files. You may use https://pastebin.com/ for secure sharing.

**Comment by dimadk24** [comment]
Hm, well, actually on Vercel there's another error now:
400 Bad request
Invalid Path

**Comment by IlyaTsupryk** [comment]
Deployed version of the app is working. I added env variables via Vercel interface after deployment, so they didn't have effect initially, but now they are applied. Some stories are not loaded because of 400 error, but the reason is in incorrect content link in the body. I'll remove them soon.
I'll share env.local with our team

**Comment by dimadk24** [comment]
Probably there's something wrong with the data, but the deployed version now doesn't work throwing JS error:
image

Locally everything is fine though. Is it because of this?
> Some stories are not loaded because of 400 error, but the reason is in incorrect content link in the body. I'll remove them soon.

**Comment by IlyaTsupryk** [comment]
That was fixed

**Review by dimadk24 — APPROVED** [review]
:+1:

**Pull request merged**
